-- V5.0.18d 系统设置归类迁移（按用户《系统设置项分类归类.xlsx》设置项归类 sheet 执行）
--   14 个旧一级分组 → 9 大一级菜单；63 个二级卡片（前端 SECTIONS 同步重写，本迁移不存二级）
--   仅改 group_name(151条) / display_name(29条) / remark(264条)；value/default/value_type 一律不动。
UPDATE system_settings SET group_name='通用设置', display_name='允许模拟支付通道', remark='允许模拟支付通道(联调用)，正式开业前必须关闭' WHERE setting_key='pay.gateway.allow_mock';
UPDATE system_settings SET group_name='通用设置' WHERE setting_key='pay.gateway.mode';
UPDATE system_settings SET group_name='通用设置', remark='支付确认查单轮询的间隔秒数' WHERE setting_key='pay.gateway.userpaying_interval_sec';
UPDATE system_settings SET group_name='通用设置', remark='微信查单轮询次数上限(用尽后可手动查单确认)' WHERE setting_key='pay.gateway.userpaying_polls';
UPDATE system_settings SET group_name='通用设置', remark='微信商户APIv3密钥，加密落库界面只显尾号' WHERE setting_key='pay.wechat.apiv3_key';
UPDATE system_settings SET group_name='通用设置', remark='微信支付绑定应用APPID' WHERE setting_key='pay.wechat.appid';
UPDATE system_settings SET group_name='通用设置', remark='微信商户API证书序列号' WHERE setting_key='pay.wechat.cert_serial';
UPDATE system_settings SET group_name='通用设置', remark='启用微信付款码V3真实支付通道' WHERE setting_key='pay.wechat.enabled';
UPDATE system_settings SET group_name='通用设置', remark='微信支付网关地址(正式/仿真联调)' WHERE setting_key='pay.wechat.gateway';
UPDATE system_settings SET group_name='通用设置', remark='微信支付商户号' WHERE setting_key='pay.wechat.mchid';
UPDATE system_settings SET group_name='通用设置', remark='微信商户API私钥全文，加密落库界面只显尾号' WHERE setting_key='pay.wechat.private_key';
UPDATE system_settings SET group_name='通用设置', remark='支付宝开放平台应用APPID' WHERE setting_key='pay.alipay.app_id';
UPDATE system_settings SET group_name='通用设置', remark='启用支付宝当面付真实支付通道' WHERE setting_key='pay.alipay.enabled';
UPDATE system_settings SET group_name='通用设置', remark='支付宝网关地址(正式/联调)' WHERE setting_key='pay.alipay.gateway';
UPDATE system_settings SET group_name='通用设置', remark='支付宝应用私钥，加密落库界面只显尾号' WHERE setting_key='pay.alipay.private_key';
UPDATE system_settings SET group_name='通用设置', remark='支付宝公钥全文，用于应答验签' WHERE setting_key='pay.alipay.public_key';
UPDATE system_settings SET group_name='AI管理', remark='俯拍多件场景的定位识别与计数' WHERE setting_key='ai.multi.enabled';
UPDATE system_settings SET group_name='AI管理', remark='多件识别逐件采信阈值' WHERE setting_key='ai.multi.min_conf';
UPDATE system_settings SET group_name='AI管理', remark='多件识别定位模型' WHERE setting_key='ai.seg.model_id';
UPDATE system_settings SET group_name='AI管理', remark='定位模型检出框最低置信度' WHERE setting_key='ai.seg.yolo_min_conf';
UPDATE system_settings SET group_name='AI管理', remark='多帧跟踪平滑(连续帧同品匹配稳定标注)' WHERE setting_key='ai.track.enabled';
UPDATE system_settings SET group_name='AI管理', remark='连续命中同一商品即标记稳定确认的帧数' WHERE setting_key='ai.track.stable_frames';
UPDATE system_settings SET group_name='AI管理', remark='向量检索图像编码引擎(PP-ShiTu/Chinese-CLIP)' WHERE setting_key='ai.feature.engine';
UPDATE system_settings SET group_name='AI管理', remark='商品识别底层引擎(条码→图像检索→模型分层调度)' WHERE setting_key='ai.engine';
UPDATE system_settings SET group_name='AI管理', remark='VL兜底与YOLO检测的最低采信置信度' WHERE setting_key='ai.fallback_conf';
UPDATE system_settings SET group_name='数据管理', remark='AI识别过程帧保留天数(到期自动清理)' WHERE setting_key='ai.frames.retention_days';
UPDATE system_settings SET group_name='AI管理', remark='专用OCR引擎HTTP地址(优先认字)' WHERE setting_key='ai.ocr.engine_url';
UPDATE system_settings SET group_name='AI管理', remark='OCR不可达时兜底的票据视觉模型' WHERE setting_key='ai.ocr.vl_model';
UPDATE system_settings SET group_name='AI管理', remark='样本向量检索主路径开关' WHERE setting_key='ai.emb.enabled';
UPDATE system_settings SET group_name='AI管理', display_name='Top1-Top2 边距(CLIP)', remark='Top1须领先Top2的最小差值(CLIP)' WHERE setting_key='ai.emb.margin';
UPDATE system_settings SET group_name='AI管理', display_name='自动采信阈值(CLIP)', remark='Top1相似度自动命中线(CLIP)' WHERE setting_key='ai.emb.min_conf';
UPDATE system_settings SET group_name='AI管理', display_name='高置信快速通道(CLIP)', remark='近样本复拍快速命中线(CLIP)' WHERE setting_key='ai.emb.strict_conf';
UPDATE system_settings SET group_name='AI管理', remark='Top1领先Top2最小差值(PP-ShiTu)' WHERE setting_key='ai.emb.pp.margin';
UPDATE system_settings SET group_name='AI管理', remark='Top1自动命中线(PP-ShiTu)' WHERE setting_key='ai.emb.pp.min_conf';
UPDATE system_settings SET group_name='AI管理', remark='近样本复拍快速命中线(PP-ShiTu)' WHERE setting_key='ai.emb.pp.strict_conf';
UPDATE system_settings SET group_name='AI管理', display_name='候选商品数', remark='向量检索返回的候选商品数' WHERE setting_key='ai.emb.topk';
UPDATE system_settings SET group_name='AI管理', remark='近30天销量对候选卡片展示排序的加成' WHERE setting_key='ai.rerank.freq_weight';
UPDATE system_settings SET group_name='AI管理', remark='图文对齐信号对候选排序的拉动权重' WHERE setting_key='ai.rerank.text_weight';
UPDATE system_settings SET group_name='AI管理', remark='新模型导入后是否自动激活并切换多件定位' WHERE setting_key='ai.autotrain.auto_activate';
UPDATE system_settings SET group_name='AI管理', remark='每周自动训练日' WHERE setting_key='ai.autotrain.day_of_week';
UPDATE system_settings SET group_name='AI管理', remark='训练用设备(GPU/CPU)' WHERE setting_key='ai.autotrain.device';
UPDATE system_settings SET group_name='AI管理', remark='按周计划自动训练总开关' WHERE setting_key='ai.autotrain.enabled';
UPDATE system_settings SET group_name='AI管理', remark='自动训练的epochs轮数' WHERE setting_key='ai.autotrain.epochs';
UPDATE system_settings SET group_name='AI管理', display_name='自动训练时长(小时)', remark='自动训练触发小时(建议凌晨)' WHERE setting_key='ai.autotrain.hour';
UPDATE system_settings SET group_name='AI管理', remark='上次自动训练运行状态(系统写回)' WHERE setting_key='ai.autotrain.last_run';
UPDATE system_settings SET group_name='AI管理', remark='低于该样本量跳过训练' WHERE setting_key='ai.autotrain.min_samples';
UPDATE system_settings SET group_name='AI管理', remark='训练用预训练底座模型' WHERE setting_key='ai.autotrain.model';
UPDATE system_settings SET group_name='AI管理', remark='服务器可用的python命令路径' WHERE setting_key='ai.autotrain.python';
UPDATE system_settings SET group_name='AI管理', remark='Ollama服务地址' WHERE setting_key='ai.llm.base';
UPDATE system_settings SET group_name='AI管理', display_name='Ollama本地大模型开关', remark='AI问答/日报使用本地大模型开关' WHERE setting_key='ai.llm.enabled';
UPDATE system_settings SET group_name='AI管理', remark='本地大模型接入方式' WHERE setting_key='ai.llm.mode';
UPDATE system_settings SET group_name='AI管理', remark='Ollama已拉取的问答模型tag' WHERE setting_key='ai.llm.model';
UPDATE system_settings SET group_name='AI管理', remark='Ollama安装/数据路径' WHERE setting_key='ai.llm.path';
UPDATE system_settings SET group_name='AI管理', remark='销量预测引擎(baseline/LightGBM)' WHERE setting_key='ai.forecast.engine';
UPDATE system_settings SET group_name='AI管理', remark='预测模型回看窗口(天)' WHERE setting_key='ai.forecast.history_days';
UPDATE system_settings SET group_name='AI管理', remark='LGBM引擎生效所需全店流水天数门槛' WHERE setting_key='ai.forecast.lgbm.min_days';
UPDATE system_settings SET group_name='AI管理', remark='本地LightGBM微服务地址' WHERE setting_key='ai.forecast.lgbm.url';
UPDATE system_settings SET group_name='AI管理', remark='门店/商圈客流地点因子(上下调预测)' WHERE setting_key='ai.forecast.location_factor';
UPDATE system_settings SET group_name='AI管理', remark='天气影响权重(0不参与，1完全跟随)' WHERE setting_key='ai.forecast.weather_weight';
UPDATE system_settings SET group_name='AI管理', remark='自定义节日表(客流倍数，可联网导入法定节日)' WHERE setting_key='ai.holiday.custom';
UPDATE system_settings SET group_name='AI管理', remark='节假日/周末备货提醒提前量' WHERE setting_key='ai.holiday.lead_days';
UPDATE system_settings SET group_name='AI管理', remark='建议补货量覆盖未来N天销量' WHERE setting_key='ai.restock.coverage_days';
UPDATE system_settings SET group_name='AI管理', remark='安全库存系数(安全库存=日均销×系数)' WHERE setting_key='ai.restock.safety_days';
UPDATE system_settings SET group_name='AI管理', remark='每日补货建议生成时刻' WHERE setting_key='ai.restock.time';
UPDATE system_settings SET group_name='AI管理', remark='天气自动备货建议纳入AI刷新' WHERE setting_key='ai.weather.auto_factor';
UPDATE system_settings SET group_name='AI管理', remark='门店所在城市(换算经纬度)' WHERE setting_key='ai.weather.city';
UPDATE system_settings SET group_name='AI管理', remark='天气因素接入开关' WHERE setting_key='ai.weather.enabled';
UPDATE system_settings SET group_name='AI管理', remark='和风天气API专属Host' WHERE setting_key='ai.weather.qweather_host';
UPDATE system_settings SET group_name='AI管理', remark='和风天气API密钥' WHERE setting_key='ai.weather.qweather_key';
UPDATE system_settings SET group_name='AI管理', remark='近90天购物篮小票共现规则缓存' WHERE setting_key='ai.assoc_rules';
UPDATE system_settings SET group_name='AI管理', remark='购物篮关联规则最低置信度' WHERE setting_key='ai.assoc.min_conf';
UPDATE system_settings SET group_name='AI管理', remark='收银行为防损基线缓存(自动学习)' WHERE setting_key='ai.fraud_baseline';
UPDATE system_settings SET group_name='AI管理', remark='交班现金差异异常阈值' WHERE setting_key='ai.fraud.cash_gap';
UPDATE system_settings SET group_name='AI管理', remark='异常折扣率阈值(0.3=30%)' WHERE setting_key='ai.fraud.discount_floor';
UPDATE system_settings SET group_name='AI管理', remark='异常折扣最小样本数(防误报)' WHERE setting_key='ai.fraud.discount_n';
UPDATE system_settings SET group_name='AI管理', remark='异常退货率阈值' WHERE setting_key='ai.fraud.return_floor';
UPDATE system_settings SET group_name='AI管理', remark='防损基线统计窗口' WHERE setting_key='ai.fraud.window_days';
UPDATE system_settings SET group_name='AI管理' WHERE setting_key='ai.suggest.auto';
UPDATE system_settings SET group_name='AI管理', remark='结算件数校验严格模式(漏扫拦截)' WHERE setting_key='antileak.count.strict';
UPDATE system_settings SET group_name='AI管理', remark='自助收银漏扫校验(件数/重量)' WHERE setting_key='antileak.selfcheckout.enabled';
UPDATE system_settings SET group_name='AI管理', remark='称重商品理论重量与实秤允许偏差' WHERE setting_key='antileak.weight.tolerance';
UPDATE system_settings SET group_name='通用设置', remark='微信/支付宝账单导入对账开关' WHERE setting_key='finance.billrecon.enabled';
UPDATE system_settings SET group_name='通用设置', remark='本地收款与平台入账的最大时间偏移' WHERE setting_key='finance.billrecon.window_seconds';
UPDATE system_settings SET group_name='会员管理', remark='生成会员AI画像(SQL聚合+Ollama人话画像)' WHERE setting_key='ai.member.portrait.enabled';
UPDATE system_settings SET group_name='会员管理', remark='单次生成画像的TOP N会员数上限' WHERE setting_key='ai.member.portrait.top';
UPDATE system_settings SET group_name='AI管理', display_name='智能决策中心', remark='智能决策中心总开关(定时生成建议)' WHERE setting_key='ai.decision.enabled';
UPDATE system_settings SET group_name='AI管理', remark='决策自动化成熟度门槛(解锁全自动条件)' WHERE setting_key='ai.decision.maturity';
UPDATE system_settings SET group_name='AI管理', remark='定价/补货两域的决策三档开关' WHERE setting_key='ai.decision.modes';
UPDATE system_settings SET group_name='AI管理', remark='决策中心最近一次全量刷新日期' WHERE setting_key='ai.last_refresh';
UPDATE system_settings SET group_name='会员管理', remark='每次生成沉默唤醒名单的最多人数' WHERE setting_key='ai.touch.limit';
UPDATE system_settings SET group_name='会员管理', remark='沉默会员判定天数(无消费且有余额/未用券)' WHERE setting_key='ai.touch.silent_days';
UPDATE system_settings SET group_name='AI管理', remark='每日AI日报生成时刻' WHERE setting_key='ai.daily_report.time';
UPDATE system_settings SET group_name='AI管理', remark='AI选品建议(动销/周转打分生成淘汰与扩容清单)' WHERE setting_key='ai.assortment.enabled';
UPDATE system_settings SET group_name='AI管理', remark='库存可售天数超过且动销低迷进入淘汰清单' WHERE setting_key='ai.assortment.max_turnover_days';
UPDATE system_settings SET group_name='AI管理', remark='选品动销观察窗口' WHERE setting_key='ai.assortment.window_days';
UPDATE system_settings SET group_name='AI管理', remark='临期调价建议允许低于进价开关' WHERE setting_key='ai.pricing.expiry_below_cost';
UPDATE system_settings SET group_name='AI管理', remark='临期预警天数' WHERE setting_key='ai.pricing.expiry_days';
UPDATE system_settings SET group_name='AI管理', remark='智能调价建议价最低毛利率底线' WHERE setting_key='ai.pricing.min_margin';
UPDATE system_settings SET group_name='AI管理', remark='滞销判定天数' WHERE setting_key='ai.pricing.stale_days';
UPDATE system_settings SET group_name='AI管理' WHERE setting_key='ai.pricing.stale_qty';
UPDATE system_settings SET remark='补货建议一键转采购单时记录预算快照' WHERE setting_key='po.suggest_budget';
UPDATE system_settings SET remark='向供应商收取的费用自动计入分红池' WHERE setting_key='recon.fee_to_dividend';
UPDATE system_settings SET remark='结算单审核通过后还需确认已付款才算完结' WHERE setting_key='recon.settle_pay_flow';
UPDATE system_settings SET remark='库存不足时仍允许退货出库(按负库存入账)' WHERE setting_key='stock.negative_return';
UPDATE system_settings SET display_name='零库存(负库存)允许销售', remark='零/负库存是否允许销售' WHERE setting_key='stock.negative_sales';
UPDATE system_settings SET display_name='零库存(负库存)允许报损', remark='零/负库存商品是否允许登记报损' WHERE setting_key='stock.loss_allow_zero';
UPDATE system_settings SET remark='入库价低于历史最低进价时拦截' WHERE setting_key='ai.ocr.low_price';
UPDATE system_settings SET remark='入库低价处理方式(拦截/提示)' WHERE setting_key='ai.ocr.low_price_mode';
UPDATE system_settings SET remark='未填保质期的商品禁止上架销售' WHERE setting_key='product.keep_days_required';
UPDATE system_settings SET remark='临期预警后须在时限内处置到位' WHERE setting_key='stock.expiry_disposal_hours';
UPDATE system_settings SET remark='临期提前提醒的档位(黄/橙两档)' WHERE setting_key='stock.expiry_warn_days';
UPDATE system_settings SET remark='条码爬虫每日补库次数上限(0禁用)' WHERE setting_key='barcode.crawler.daily_limit';
UPDATE system_settings SET display_name='条码爬虫补库(必应兜底)', remark='全部数据源未命中时必应兜底补库' WHERE setting_key='barcode.crawler.enable';
UPDATE system_settings SET remark='输码/扫码后自动查询本店库与在线条码库预填' WHERE setting_key='barcode.lookup.enable';
UPDATE system_settings SET display_name='在线条码库 AppID(mxnzp)', remark='在线条码库(mxnzp)数据源AppID' WHERE setting_key='barcode.lookup.mxnzp.app_id';
UPDATE system_settings SET display_name='在线条码库密钥(mxnzp)', remark='在线条码库(mxnzp)数据源密钥' WHERE setting_key='barcode.lookup.mxnzp.app_secret';
UPDATE system_settings SET group_name='营销管理', remark='多券使用规则(手动/单张/自动取最优惠)' WHERE setting_key='coupon.mode';
UPDATE system_settings SET group_name='营销管理', remark='优惠券与促销活动同单叠加开关' WHERE setting_key='coupon.stack_with_promo';
UPDATE system_settings SET group_name='营销管理', remark='临期N天自动按档位折价规则' WHERE setting_key='promo.expiry_auto_discount';
UPDATE system_settings SET group_name='营销管理', display_name='临期自动折扣(收银)', remark='收银结算时对临期商品自动折扣' WHERE setting_key='promo.expiry_auto.enabled';
UPDATE system_settings SET group_name='营销管理', remark='行级优惠与整单级优惠跨层叠加开关' WHERE setting_key='promo.stack_layers';
UPDATE system_settings SET group_name='营销管理', remark='同单命中多个促销时自动取对顾客最优惠' WHERE setting_key='promo.take_best';
UPDATE system_settings SET group_name='会员管理', remark='会员可在H5手机号自助注册建档' WHERE setting_key='member.h5.allow_register';
UPDATE system_settings SET group_name='会员管理', remark='会员掌上门户总开关' WHERE setting_key='member.h5.enabled';
UPDATE system_settings SET group_name='会员管理', remark='会员手机访问的H5入口完整地址' WHERE setting_key='member.h5.entry_url';
UPDATE system_settings SET group_name='会员管理', remark='允许会员在H5用密码登录' WHERE setting_key='member.login.password_h5';
UPDATE system_settings SET group_name='会员管理', remark='会员建档勾选的隐私协议全文' WHERE setting_key='member.privacy_text';
UPDATE system_settings SET group_name='营销管理', display_name='营销引擎每日执行时间', remark='营销引擎每日执行时刻(扫描生日/临期/分红触达)' WHERE setting_key='marketing.run_time';
UPDATE system_settings SET group_name='营销管理', remark='未达免邮门槛时收取的配送费' WHERE setting_key='delivery.fee';
UPDATE system_settings SET group_name='营销管理', remark='订单免配送费金额门槛' WHERE setting_key='delivery.free_above';
UPDATE system_settings SET group_name='营销管理', remark='配送半径(0不限，超出拒绝)' WHERE setting_key='delivery.radius_km';
UPDATE system_settings SET group_name='营销管理', remark='开通在线配送(配送/外卖下单)' WHERE setting_key='delivery.serving';
UPDATE system_settings SET group_name='营销管理', remark='配送围栏圆心纬度' WHERE setting_key='store.lat';
UPDATE system_settings SET group_name='营销管理', remark='配送围栏圆心经度' WHERE setting_key='store.lng';
UPDATE system_settings SET group_name='营销管理', remark='扫码购允许选微信/支付宝付款' WHERE setting_key='h5.direct_pay';
UPDATE system_settings SET group_name='营销管理', remark='线上商城/扫码购移动端总开关' WHERE setting_key='h5.enabled';
UPDATE system_settings SET group_name='营销管理', remark='扫码购单笔应付上限(元)' WHERE setting_key='h5.scan_go_limit';
UPDATE system_settings SET remark='成长值体系总开关' WHERE setting_key='member.growth.enabled';
UPDATE system_settings SET display_name='成长值排除(分类)', remark='成长值排除分类(整类消费不计)' WHERE setting_key='member.growth.exclude_categories';
UPDATE system_settings SET display_name='成长值排除(商品)', remark='成长值排除商品(如香烟)' WHERE setting_key='member.growth.exclude_products';
UPDATE system_settings SET remark='特价/折扣活动商品消费不计成长' WHERE setting_key='member.growth.exclude_promo';
UPDATE system_settings SET remark='每充值1元本金计多少成长值' WHERE setting_key='member.growth.recharge_rate';
UPDATE system_settings SET remark='每实付消费1元计多少成长值' WHERE setting_key='member.growth.consume_rate';
UPDATE system_settings SET remark='等级考核滚动窗口月数' WHERE setting_key='member.growth.period_months';
UPDATE system_settings SET remark='等级保护缓冲期(天)，期内保留权益' WHERE setting_key='member.level_grace_days';
UPDATE system_settings SET remark='每日按昨日净利自动计提分红(与手动互斥)' WHERE setting_key='dividend.auto.enabled';
UPDATE system_settings SET remark='每日自动分红计提与失效回冲触发时刻' WHERE setting_key='dividend.auto.time';
UPDATE system_settings SET remark='分红终身封顶比例(累计充值×比例)' WHERE setting_key='dividend.cap_rate';
UPDATE system_settings SET remark='分红有效期，过期作废' WHERE setting_key='dividend.expire_days';
UPDATE system_settings SET remark='有效消费单笔金额门槛(防微额刷单)' WHERE setting_key='dividend.min_single';
UPDATE system_settings SET remark='统计窗口内累计消费资格线' WHERE setting_key='dividend.min_window';
UPDATE system_settings SET remark='分红年化橙色预警线' WHERE setting_key='dividend.orange_alert';
UPDATE system_settings SET remark='分红池比例(昨日净利润×比例)' WHERE setting_key='dividend.ratio';
UPDATE system_settings SET remark='分红年化红色预警线(须立即干预)' WHERE setting_key='dividend.red_alert';
UPDATE system_settings SET remark='有效消费窗口天数' WHERE setting_key='dividend.window_days';
UPDATE system_settings SET remark='按会员等级打折计价的开关' WHERE setting_key='member.level_discount';
UPDATE system_settings SET remark='断网时允许会员余额先记账后清算' WHERE setting_key='member.offline.enabled';
UPDATE system_settings SET remark='断网挂账当日累计限额' WHERE setting_key='member.offline.max_daily';
UPDATE system_settings SET remark='断网挂账单笔限额' WHERE setting_key='member.offline.max_single';
UPDATE system_settings SET remark='会员H5发起充值的单笔上限' WHERE setting_key='member.recharge.max_single';
UPDATE system_settings SET remark='充值单超过该时长未支付即失效' WHERE setting_key='member.recharge.orders_expire_hours';
UPDATE system_settings SET remark='月房租总额(日摊计入每日净利)' WHERE setting_key='store.cost.rent';
UPDATE system_settings SET remark='月水电燃气等总额(日摊计入净利)' WHERE setting_key='store.cost.utility';
UPDATE system_settings SET remark='设备装修等按月折旧摊销额(日摊计入净利)' WHERE setting_key='store.cost.depreciation';
UPDATE system_settings SET remark='物业/网费等月其他固定支出' WHERE setting_key='store.cost.other';
UPDATE system_settings SET group_name='通用设置', remark='收银台结算页可直接套用的整单折扣预设规则' WHERE setting_key='pos.discount.presets';
UPDATE system_settings SET group_name='通用设置', remark='取单列表默认范围：本人挂单或全店挂单' WHERE setting_key='pos.held.default_scope';
UPDATE system_settings SET group_name='通用设置', remark='收银员改价/打折的授权频次(一次授权或每次输码)' WHERE setting_key='pos.price.auth_reuse';
UPDATE system_settings SET group_name='通用设置', remark='持授权权限的员工本人操作价格是否免输授权码' WHERE setting_key='pos.price.auth_self';
UPDATE system_settings SET group_name='通用设置' WHERE setting_key='pos.cashbox.float_default';
UPDATE system_settings SET group_name='通用设置', remark='挂账单默认到期天数' WHERE setting_key='pos.credit.due_days';
UPDATE system_settings SET group_name='通用设置', remark='交接班现金差异容差(超过需填原因)' WHERE setting_key='pos.shift.diff_tolerance';
UPDATE system_settings SET group_name='会员管理', remark='积分抵现单笔上限(占应收百分比)' WHERE setting_key='pos.points.max_pct';
UPDATE system_settings SET group_name='会员管理', display_name='积分抵现比例', remark='积分抵现比例(多少积分抵1元)' WHERE setting_key='pos.points.rate';
UPDATE system_settings SET group_name='通用设置', remark='未设最低卖价时的最低售价兜底比率(价格红线)' WHERE setting_key='sales.floor_guard_rate';
UPDATE system_settings SET group_name='通用设置', remark='同码连扫防抖，避免重复加件' WHERE setting_key='pos.cashier.debounce';
UPDATE system_settings SET group_name='通用设置', remark='收银台每行商品数的初始默认值' WHERE setting_key='pos.cashier.grid_cols';
UPDATE system_settings SET group_name='通用设置', remark='收银台键盘快捷键映射JSON' WHERE setting_key='pos.cashier.hotkey_map';
UPDATE system_settings SET group_name='通用设置', remark='键盘快捷键功能的默认开关' WHERE setting_key='pos.cashier.hotkeys';
UPDATE system_settings SET group_name='通用设置', remark='收银台无操作自动锁屏闲置超时' WHERE setting_key='pos.cashier.lock_timeout';
UPDATE system_settings SET group_name='通用设置', remark='新版收银台开关(可回退旧版视图)' WHERE setting_key='pos.cashier.new_ui';
UPDATE system_settings SET group_name='通用设置', remark='收银台快捷商品区默认展示格数' WHERE setting_key='pos.cashier.quick_count';
UPDATE system_settings SET group_name='通用设置', remark='库存硬拦：账实不符时拒绝或按负库存售卖' WHERE setting_key='pos.cashier.stock_hard';
UPDATE system_settings SET group_name='通用设置', remark='收款成功后语音播报金额的总开关' WHERE setting_key='pos.cashier.tts';
UPDATE system_settings SET group_name='通用设置', remark='收银台专用播报语速(留空跟随全局)' WHERE setting_key='pos.cashier.tts.rate';
UPDATE system_settings SET group_name='通用设置', remark='收银台专用播报音色(留空跟随全局)' WHERE setting_key='pos.cashier.tts.voice';
UPDATE system_settings SET group_name='连锁管理', remark='新会员注册/建档归属的总部门店ID' WHERE setting_key='member.hq_store_id';
UPDATE system_settings SET remark='商店名称，用于小票抬头/收银台门头' WHERE setting_key='store.info.name';
UPDATE system_settings SET remark='浮层/支付弹层的液态玻璃磨砂质感效果' WHERE setting_key='ui.glass.enabled';
UPDATE system_settings SET group_name='数据管理', remark='审计日志保留天数(0关闭清理)' WHERE setting_key='auth.audit_retention';
UPDATE system_settings SET remark='员工/会员密码强度策略' WHERE setting_key='auth.password_policy';
UPDATE system_settings SET remark='大额单据的签字确认方式(现场补签/短信)' WHERE setting_key='auth.sign_large_mode';
UPDATE system_settings SET remark='必须签字才能过审的单据类型' WHERE setting_key='auth.sign_required_scenes';
UPDATE system_settings SET remark='大额签字阈值' WHERE setting_key='auth.sign_threshold';
UPDATE system_settings SET remark='现金收款结账成功后自动弹开钱箱' WHERE setting_key='pos.drawer.enabled';
UPDATE system_settings SET remark='收银端与服务器心跳超时(触发离线收银引导)' WHERE setting_key='pos.heartbeat_timeout';
UPDATE system_settings SET remark='应急价目表新鲜度上限(超时禁止应急收银)' WHERE setting_key='pos.pricebook_fresh_hours';
UPDATE system_settings SET remark='收银合计金额的抹零规则' WHERE setting_key='pos.round_rule';
UPDATE system_settings SET remark='退款免审限额(超过则创建待审核)' WHERE setting_key='sales.refund.limit';
UPDATE system_settings SET display_name='退货时限(按分类)', remark='按商品分类设置的退货时限' WHERE setting_key='sales.refund.window_by_category';
UPDATE system_settings SET display_name='退货时限(天)', remark='全局退货时限(天)' WHERE setting_key='sales.refund.window_days';
UPDATE system_settings SET remark='待付款订单自动关单超时(先查支付通道确认未支付)' WHERE setting_key='sales.close_order_minutes';
UPDATE system_settings SET remark='临期商品豁免成交价下限闸，允许低于进价销售' WHERE setting_key='sales.floor_guard_expiry_exempt';
UPDATE system_settings SET remark='成交价下限闸：优惠叠加低于最低售价时需店长授权' WHERE setting_key='sales.price_floor_guard';
UPDATE system_settings SET remark='会员端自助扫码购功能开关' WHERE setting_key='sales.scanpay_enabled';
UPDATE system_settings SET remark='移动收银与作业模块的左右手镜像习惯' WHERE setting_key='mobile.hand';
UPDATE system_settings SET group_name='数据管理', remark='库存流水归档月数(超期迁移归档表)' WHERE setting_key='ops.archive.flow_months';
UPDATE system_settings SET group_name='数据管理', remark='AI识别日志归档月数' WHERE setting_key='ops.archive.recog_months';
UPDATE system_settings SET group_name='数据管理', remark='每日全量+双硬盘轮换备份时间' WHERE setting_key='ops.backup_hour';
UPDATE system_settings SET remark='应急收银单笔金额上限' WHERE setting_key='ops.emergency_amount_cap';
UPDATE system_settings SET remark='允许执行应急收银的角色' WHERE setting_key='ops.emergency_pay';
UPDATE system_settings SET remark='日销售目标(>0时日报显示达成率)' WHERE setting_key='report.daily_target';
UPDATE system_settings SET remark='条码秤条码格式模板' WHERE setting_key='ai.scale.barcode_format';
UPDATE system_settings SET remark='秤码校验位按EAN mod10验算开关' WHERE setting_key='ai.scale.check_verify';
UPDATE system_settings SET remark='自定义秤码格式' WHERE setting_key='ai.scale.custom_format';
UPDATE system_settings SET display_name='秤签有效期(天)', remark='秤签有效期(天)，超期拒收' WHERE setting_key='ai.scale.label_valid_days';
UPDATE system_settings SET remark='PWA作业页未读经营告警的语音播报开关' WHERE setting_key='ai.voice.alerts';
UPDATE system_settings SET remark='审核通过后自动弹出A5单据打印' WHERE setting_key='doc.print.auto_a5';
UPDATE system_settings SET remark='打印机USB刷新后静默自动重连总闸' WHERE setting_key='ops.printer_reconnect';
UPDATE system_settings SET remark='电子秤串口波特率' WHERE setting_key='scale.baud';
UPDATE system_settings SET remark='电子秤自动读重总开关' WHERE setting_key='scale.enabled';
UPDATE system_settings SET remark='条码秤打印条码的前两位识别码' WHERE setting_key='scale.tx.barcode_prefix';
UPDATE system_settings SET remark='默认波特率' WHERE setting_key='scale.tx.baud';
UPDATE system_settings SET remark='秤端编码(中文标签秤通用GBK)' WHERE setting_key='scale.tx.charset';
UPDATE system_settings SET remark='默认部门号' WHERE setting_key='scale.tx.department';
UPDATE system_settings SET remark='默认串口号' WHERE setting_key='scale.tx.port';
UPDATE system_settings SET remark='默认连接方式(串口/网口)' WHERE setting_key='scale.tx.port_type';
UPDATE system_settings SET remark='默认协议品牌' WHERE setting_key='scale.tx.protocol';
UPDATE system_settings SET remark='网口秤IP' WHERE setting_key='scale.tx.tcp_host';
UPDATE system_settings SET remark='网口秤端口' WHERE setting_key='scale.tx.tcp_port';
UPDATE system_settings SET remark='是否同步下发会员价到秤' WHERE setting_key='scale.tx.use_member_price';
UPDATE system_settings SET remark='老板端经营问答答案自动朗读开关' WHERE setting_key='voice.assistant.enabled';
UPDATE system_settings SET remark='语音提问查价的回答播报开关' WHERE setting_key='voice.price.enabled';
UPDATE system_settings SET remark='收银加购时播报商品名+价格开关' WHERE setting_key='voice.product.enabled';
UPDATE system_settings SET remark='播报语速(0.5~2倍)' WHERE setting_key='voice.tts.rate';
UPDATE system_settings SET remark='播报音色(空=自动选最佳中文声)' WHERE setting_key='voice.tts.voice';
UPDATE system_settings SET display_name='收银机授权(设备白名单)', remark='员工登录必须使用已授权设备(设备白名单)' WHERE setting_key='pos.device.auth';
UPDATE system_settings SET display_name='本机(127.0.0.1)免设备授权', remark='服务器本机(127.0.0.1)登录跳过设备授权' WHERE setting_key='pos.device.auth.loopback.bypass';
UPDATE system_settings SET display_name='设备绑定员工(一机一人)', remark='设备绑定员工(一机一人)开关' WHERE setting_key='pos.device.bind.employee';
UPDATE system_settings SET remark='收银员/库管可授权的设备数' WHERE setting_key='pos.device.limit.cashier';
UPDATE system_settings SET remark='店长/财务/管理员可授权的设备数' WHERE setting_key='pos.device.limit.manager';
UPDATE system_settings SET remark='单个配对码可用次数' WHERE setting_key='pos.device.pair.max.uses';
UPDATE system_settings SET display_name='配对码有效期(小时)', remark='配对码有效期(小时)' WHERE setting_key='pos.device.pair.ttl.hours';
UPDATE system_settings SET remark='设备授权应急恢复码(超管兜底)' WHERE setting_key='pos.device.recovery.hint';
UPDATE system_settings SET display_name='强制设备签名校验(P1)', remark='强制设备硬件签名校验' WHERE setting_key='pos.device.require.signature';
UPDATE system_settings SET remark='单账号单设备在线(防多地同时收银)' WHERE setting_key='pos.device.single.session';
UPDATE system_settings SET remark='单门店可登记授权设备总量上限' WHERE setting_key='pos.device.store.cap';
UPDATE system_settings SET remark='顾客副屏空闲轮播内容' WHERE setting_key='display.ads';
UPDATE system_settings SET remark='顾客副屏顶栏常驻欢迎语' WHERE setting_key='display.welcome';
UPDATE system_settings SET display_name='全屏强制置顶(强 Kiosk)', remark='收银台全屏强制置顶(强Kiosk)' WHERE setting_key='pos.desktop.kiosk_topmost';
UPDATE system_settings SET remark='主屏向顾客副屏推送购物明细/支付引导' WHERE setting_key='pos.display.push';
UPDATE system_settings SET display_name='结账自动打印小票(小票机)', remark='结账自动打印小票(小票机)总开关' WHERE setting_key='pos.print.auto';
UPDATE system_settings SET remark='未配置小票机时浏览器兜底打印' WHERE setting_key='pos.print.browser_fallback';
UPDATE system_settings SET remark='每单小票打印联数' WHERE setting_key='pos.print.copies';
UPDATE system_settings SET display_name='浏览器打印小票(无小票机时)', remark='浏览器打印路径的自动出票开关' WHERE setting_key='pos.receipt.auto_print';
UPDATE system_settings SET remark='小票纸宽度(mm)' WHERE setting_key='pos.receipt.width';
UPDATE system_settings SET remark='收银完成后的收款金额语音提示开关' WHERE setting_key='pos.voice_broadcast';
UPDATE system_settings SET group_name='数据管理', remark='门店开业日期，作为经营报表起算日与分红资格窗口基准' WHERE setting_key='init.opening_date';
UPDATE system_settings SET group_name='数据管理', remark='开业日向全员广播一次的开业说明' WHERE setting_key='init.opening_note';
UPDATE system_settings SET group_name='数据管理', remark='最多保留的备份份数' WHERE setting_key='ops.backup.keep_count';
UPDATE system_settings SET group_name='数据管理', remark='备份目录总占用上限(GB)' WHERE setting_key='ops.backup.max_total_gb';
UPDATE system_settings SET remark='进价差异单超时未裁决自动结案并升级告警' WHERE setting_key='chain.cost.adjust_window_h';
UPDATE system_settings SET remark='新品首进自动采纳实际进价作为标准进价' WHERE setting_key='chain.cost.auto_adopt_new';
UPDATE system_settings SET remark='同店同商品同向进价差异单合并窗口' WHERE setting_key='chain.cost.merge_days';
UPDATE system_settings SET remark='门店申请新商品上架是否免总部批准' WHERE setting_key='chain.product.self_apply';
UPDATE system_settings SET remark='跨店退货是否允许受理店现金直接退付' WHERE setting_key='chain.return.cross_cash';
UPDATE system_settings SET remark='盘点盈余按棘轮规则允许抬高L1进价基准' WHERE setting_key='chain.variance.pickup_raise_l1';
UPDATE system_settings SET remark='单节点单日退款/回补入向总额上限(防增发)' WHERE setting_key='hq.member.cross_daily_limit';
