-- V5.0.18e 恢复设置项说明（remark）：迁移180曾用提炼版「功能摘要」覆盖，现按用户表「原始说明」列恢复为原文。
--   group_name / display_name（新归类与新名称）保持不变。
UPDATE system_settings SET remark='开=允许 mock 假扣款(联调用，付款码尾号 0000 模拟失败)；【正式开业前必须关闭】——关闭后扫码支付只走真实通道，收银台结算弹窗不再出现模拟通道提示' WHERE setting_key='pay.gateway.allow_mock';
UPDATE system_settings SET remark='支付通道模式：扫码收款走真实扣款还是记账留痕' WHERE setting_key='pay.gateway.mode';
UPDATE system_settings SET remark='查单轮询的间隔秒数；次数×间隔 = 最长等待时间' WHERE setting_key='pay.gateway.userpaying_interval_sec';
UPDATE system_settings SET remark='微信返回 USERPAYING(顾客输入密码中)时自动查单轮询次数；用尽后可稍后手动查单确认' WHERE setting_key='pay.gateway.userpaying_polls';
UPDATE system_settings SET remark='32 位 APIv3 密钥——加密落库，界面只显尾号；留空保存=不修改' WHERE setting_key='pay.wechat.apiv3_key';
UPDATE system_settings SET remark='绑定的公众号/小程序/APP appid' WHERE setting_key='pay.wechat.appid';
UPDATE system_settings SET remark='商户API证书序列号(商户平台 API 安全页)' WHERE setting_key='pay.wechat.cert_serial';
UPDATE system_settings SET remark='real 模式下微信付款码走微信支付 V3 codepay；需填齐商户号/APPID/APIv3密钥/证书序列号/商户私钥' WHERE setting_key='pay.wechat.enabled';
UPDATE system_settings SET remark='正式网关；仿真/联调可改(如微信支付仿真系统)' WHERE setting_key='pay.wechat.gateway';
UPDATE system_settings SET remark='微信支付商户平台 mchid，如 1900000109' WHERE setting_key='pay.wechat.mchid';
UPDATE system_settings SET remark='apiclient_key.pem 全文(BEGIN PRIVATE KEY)——加密落库，界面只显尾号' WHERE setting_key='pay.wechat.private_key';
UPDATE system_settings SET remark='开放平台应用 APPID，需签约「当面付」' WHERE setting_key='pay.alipay.app_id';
UPDATE system_settings SET remark='real 模式下支付宝付款码走当面付 alipay.trade.pay；需填齐 APPID/应用私钥/支付宝公钥' WHERE setting_key='pay.alipay.enabled';
UPDATE system_settings SET remark='正式网关；沙箱联调改 https://openapi-sandbox.dl.alipaydev.com/gateway.do' WHERE setting_key='pay.alipay.gateway';
UPDATE system_settings SET remark='应用私钥(PKCS8)全文——加密落库，界面只显尾号；留空保存=不修改' WHERE setting_key='pay.alipay.private_key';
UPDATE system_settings SET remark='支付宝公钥全文——加密落库，用于应答验签；留空保存=不修改' WHERE setting_key='pay.alipay.public_key';
UPDATE system_settings SET remark='俯拍多件场景：定位(「多件定位模型」或零训练轮廓分割)→ 逐件裁剪向量检索 → 按商品聚合计数；单件画面自动回落单件管线' WHERE setting_key='ai.multi.enabled';
UPDATE system_settings SET remark='多件识别逐件采信阈值；低于该值回落为候选卡片由店员确认' WHERE setting_key='ai.multi.min_conf';
UPDATE system_settings SET remark='多件识别定位模型(ai_models.id，建议单类 detect 模型；0=轮廓分割兜底，backend/ai-train 训练包产出)' WHERE setting_key='ai.seg.model_id';
UPDATE system_settings SET remark='定位模型检出框的最低置信度(低于则丢弃该框)' WHERE setting_key='ai.seg.yolo_min_conf';
UPDATE system_settings SET remark='连续帧同品命中做 IoU/同品匹配与稳定标注(不改变命中判定门槛)' WHERE setting_key='ai.track.enabled';
UPDATE system_settings SET remark='连续命中同一商品达到该帧数即标记「稳定确认」' WHERE setting_key='ai.track.stable_frames';
UPDATE system_settings SET remark='识别「向量检索层」的图像编码引擎：把识别帧/裁剪件编码成向量，再与样本库向量比对。auto=PP-ShiTuV2 模型文件(backend/models/ppshituv2_general.onnx)存在即用之，缺失自动回退 Chinese-CLIP。两引擎阈值各自成组：ai.emb.pp.*(PP)与 ai.emb.*(CLIP)；切换后旧向量视为过期，需在 AI 训练台重建索引。PP-ShiTu 无文本塔，「瓶身文字佐证」仅在 Chinese-CLIP 引擎下生效' WHERE setting_key='ai.feature.engine';
UPDATE system_settings SET remark='商品识别的底层引擎；实际收银时仍按「条码 → 图像检索 → 模型」自动分层调度。原「模拟联调 mock」选项已删除：其实现早已是真实的 dHash 样本匹配，与 sample 相同，为避免误导已合并' WHERE setting_key='ai.engine';
UPDATE system_settings SET remark='VL 兜底识别与 YOLO 检测(识别引擎=vl/yolo)的最低采信置信度，低于该值的检出结果被丢弃；并非「低于它才触发兜底」的开关' WHERE setting_key='ai.fallback_conf';
UPDATE system_settings SET remark='AI 识别过程帧只保留 N 天，到期自动清理释放磁盘(每 6 小时执行一轮)；已进样本库的图片不受影响永久保留；0=关闭自动清理' WHERE setting_key='ai.frames.retention_days';
UPDATE system_settings SET remark='专用 OCR 引擎(如 PaddleOCR)的 HTTP 地址，例如 http://127.0.0.1:9000/ocr。优先用它认字；留空或不可达时才回退到下方「票据OCR视觉模型」看图识字(二者是两级串联，不重复)' WHERE setting_key='ai.ocr.engine_url';
UPDATE system_settings SET remark='票据/证照识别的主力是「OCR引擎地址」的专用 OCR(认字快而准，不用大模型)；本项仅当 OCR 未配置或不可达时才兜底"看图识字"——正常部署了 OCR 就用不上它' WHERE setting_key='ai.ocr.vl_model';
UPDATE system_settings SET remark='实时识别的图像主路径：样本向量检索(毫秒级，编码引擎见「向量检索特征引擎」)；关闭后直接走 dHash/VL 兜底。本组阈值适用于 Chinese-CLIP 引擎，PP-ShiTu 引擎请用 ai.emb.pp.* 同名项' WHERE setting_key='ai.emb.enabled';
UPDATE system_settings SET remark='Top1 须领先 Top2 至少该差值才自动命中；不足则转候选卡片由店员点选。适用于 Chinese-CLIP 引擎，PP-ShiTu 引擎请用 ai.emb.pp.margin' WHERE setting_key='ai.emb.margin';
UPDATE system_settings SET remark='Top-1 相似度达到该值自动命中；未达则携带候选卡片走兜底/人工确认。适用于 Chinese-CLIP 引擎，PP-ShiTu 引擎请用 ai.emb.pp.min_conf' WHERE setting_key='ai.emb.min_conf';
UPDATE system_settings SET remark='Top-1 达到该值视为近乎样本复拍，无需边距直接命中。适用于 Chinese-CLIP 引擎，PP-ShiTu 引擎请用 ai.emb.pp.strict_conf' WHERE setting_key='ai.emb.strict_conf';
UPDATE system_settings SET remark='PP-ShiTu 引擎的 Top1 领先 Top2 的最小差值，不足则转候选卡片' WHERE setting_key='ai.emb.pp.margin';
UPDATE system_settings SET remark='PP-ShiTu 引擎的 Top-1 相似度自动命中线(PP 空间量纲与 CLIP 完全不同，勿与 ai.emb.min_conf 混用)' WHERE setting_key='ai.emb.pp.min_conf';
UPDATE system_settings SET remark='PP-ShiTu 引擎的近乎样本复拍快速命中线(无需边距直接命中)' WHERE setting_key='ai.emb.pp.strict_conf';
UPDATE system_settings SET remark='向量检索返回的候选商品数(识别→候选卡片→店员点选确认)' WHERE setting_key='ai.emb.topk';
UPDATE system_settings SET remark='近30天销量对候选卡片展示顺序的加成(只影响展示排序，不影响命中判定)' WHERE setting_key='ai.rerank.freq_weight';
UPDATE system_settings SET remark='图文对齐信号对候选排序的最大拉动(0~0.3，越大越信瓶身文字)。注意：瓶身文字佐证仅在 Chinese-CLIP 引擎下生效，PP-ShiTu 无文本塔，此项自动失效' WHERE setting_key='ai.rerank.text_weight';
UPDATE system_settings SET remark='开=新模型导入后自动激活并切换多件定位；关=训练台人工确认后激活(推荐先关)' WHERE setting_key='ai.autotrain.auto_activate';
UPDATE system_settings SET remark='每周几自动训练(建议选收银最闲的日子)' WHERE setting_key='ai.autotrain.day_of_week';
UPDATE system_settings SET remark='训练用哪个设备：有 NVIDIA 显卡选 GPU；没有选 CPU(速度慢很多)' WHERE setting_key='ai.autotrain.device';
UPDATE system_settings SET remark='开=按周计划自动执行：导出数据集→GPU训练→导入模型库(默认不自动激活，训练台确认后手动激活)' WHERE setting_key='ai.autotrain.enabled';
UPDATE system_settings SET remark='自动训练的 epochs(样本多可适当调大)' WHERE setting_key='ai.autotrain.epochs';
UPDATE system_settings SET remark='0~23，到点触发(建议 2，即凌晨 2 点)' WHERE setting_key='ai.autotrain.hour';
UPDATE system_settings SET remark='系统自动写回(时间/阶段/结果/日志尾部)，勿手工改' WHERE setting_key='ai.autotrain.last_run';
UPDATE system_settings SET remark='已入库样本少于该值时自动跳过本次训练(避免无效训练)' WHERE setting_key='ai.autotrain.min_samples';
UPDATE system_settings SET remark='训练用哪个预训练底座，一般用默认即可' WHERE setting_key='ai.autotrain.model';
UPDATE system_settings SET remark='服务器上可用的 python 命令(或完整路径，如 C:\\Python312\\python.exe)' WHERE setting_key='ai.autotrain.python';
UPDATE system_settings SET remark='Ollama 服务地址(如 http://127.0.0.1:11434)，仅本地大模型开启时使用' WHERE setting_key='ai.llm.base';
UPDATE system_settings SET remark='开启后 AI 问答/日报由本地 Ollama 大模型生成，未就绪自动回落规则引擎' WHERE setting_key='ai.llm.enabled';
UPDATE system_settings SET remark='本地大模型的接入方式；未接入时问答/日报走规则引擎' WHERE setting_key='ai.llm.mode';
UPDATE system_settings SET remark='Ollama 已拉取的模型 tag' WHERE setting_key='ai.llm.model';
UPDATE system_settings SET remark='手动识别时填写(可含 models/manifests)，留空则仅按服务地址探测' WHERE setting_key='ai.llm.path';
UPDATE system_settings SET remark='销量预测引擎；LightGBM 需本地模型服务已部署且数据量达标，失败自动回落规则引擎' WHERE setting_key='ai.forecast.engine';
UPDATE system_settings SET remark='预测模型回看窗口' WHERE setting_key='ai.forecast.history_days';
UPDATE system_settings SET remark='全店累计有流水天数达到该值才允许 lgbm 引擎生效(8 周起步，防过拟合空转)' WHERE setting_key='ai.forecast.lgbm.min_days';
UPDATE system_settings SET remark='本地 Python LightGBM 微服务(ai-forecast-svc/)；未部署时保持 baseline 引擎即可' WHERE setting_key='ai.forecast.lgbm.url';
UPDATE system_settings SET remark='多因子预测地点因子：>1 上调预测(如社区密集/临街)，<1 下调(如位置偏僻)；直接乘在预测基线上' WHERE setting_key='ai.forecast.location_factor';
UPDATE system_settings SET remark='多因子预测天气权重 w：预测量 = 基线 × (1−w + w×天气客流系数)；0=不参与，1=完全跟随天气' WHERE setting_key='ai.forecast.weather_weight';
UPDATE system_settings SET remark='在系统内置节日之外补充自定义节日(如店庆日)：填名称、月、日和客流倍数，供备货建议参考；可逐行编辑，也可联网一键导入法定节日' WHERE setting_key='ai.holiday.custom';
UPDATE system_settings SET remark='节日/周末备货提醒提前量(生成备货建议清单)' WHERE setting_key='ai.holiday.lead_days';
UPDATE system_settings SET remark='建议补货量覆盖未来 N 天销量' WHERE setting_key='ai.restock.coverage_days';
UPDATE system_settings SET remark='安全库存 = 日均销 × 系数' WHERE setting_key='ai.restock.safety_days';
UPDATE system_settings SET remark='每日定时(HH:MM，进程内检查)' WHERE setting_key='ai.restock.time';
UPDATE system_settings SET remark='开=每日天气备货建议纳入 AI 刷新(ai.weather.enabled 的数据源开关之下)；关=跳过天气备货' WHERE setting_key='ai.weather.auto_factor';
UPDATE system_settings SET remark='填写门店所在城市名(如：北京/上海/杭州)，系统自动换算经纬度；请改成门店实际所在城市' WHERE setting_key='ai.weather.city';
UPDATE system_settings SET remark='测试' WHERE setting_key='ai.weather.enabled';
UPDATE system_settings SET remark='和风天气 API Host(新账号为专属 Host，见和风控制台)；仅在填写 Key 后生效' WHERE setting_key='ai.weather.qweather_host';
UPDATE system_settings SET remark='测试' WHERE setting_key='ai.weather.qweather_key';
UPDATE system_settings SET remark='近 90 天小票共现(自动重建)' WHERE setting_key='ai.assoc_rules';
UPDATE system_settings SET remark='购物篮规则的最低可信度(0~1，越高规则越严格)' WHERE setting_key='ai.assoc.min_conf';
UPDATE system_settings SET remark='收银行为基线(自动学习)' WHERE setting_key='ai.fraud_baseline';
UPDATE system_settings SET remark='交班现金差异绝对值超该值记异常' WHERE setting_key='ai.fraud.cash_gap';
UPDATE system_settings SET remark='折扣力度超过商品原价该比例记异常折扣单(0.3 = 30%)' WHERE setting_key='ai.fraud.discount_floor';
UPDATE system_settings SET remark='单班异常折扣单数 ≥ 该值才告警(防误报)' WHERE setting_key='ai.fraud.discount_n';
UPDATE system_settings SET remark='近 30 天退货单占比超过该值记异常(0.1 = 10%)' WHERE setting_key='ai.fraud.return_floor';
UPDATE system_settings SET remark='收银行为基线统计窗口' WHERE setting_key='ai.fraud.window_days';
UPDATE system_settings SET remark='每日自动生成智能经营建议' WHERE setting_key='ai.suggest.auto';
UPDATE system_settings SET remark='严格=结算件数少于识别件数即拦截；宽松=仅缺件 ≥2 时拦截' WHERE setting_key='antileak.count.strict';
UPDATE system_settings SET remark='扫码购/自助结算时校验 AI 识别件数 vs 结算件数、理论重量 vs 实秤重量；差异即暂停待店员复核' WHERE setting_key='antileak.selfcheckout.enabled';
UPDATE system_settings SET remark='称重商品理论重量与实秤重量允许偏差；超出即判定重量差异' WHERE setting_key='antileak.weight.tolerance';
UPDATE system_settings SET remark='微信/支付宝账单 CSV 导入 → 金额+时间窗口对齐本地流水 → 差异清单进日结' WHERE setting_key='finance.billrecon.enabled';
UPDATE system_settings SET remark='本地收款时间与平台入账时间的最大允许偏移；平台入账有延迟，默认 ±5 分钟' WHERE setting_key='finance.billrecon.window_seconds';
UPDATE system_settings SET remark='开启后「生成会员画像」用 SQL 聚合常购商品/品类偏好/到店时段/价格带/流失前兆，Ollama 开启时额外生成一人一段人话画像(数据不出店)' WHERE setting_key='ai.member.portrait.enabled';
UPDATE system_settings SET remark='单次生成按近 180 天消费额取 TOP N 位会员(大模型逐人生成耗时，防阻塞)' WHERE setting_key='ai.member.portrait.top';
UPDATE system_settings SET remark='总开关：关则定时不自动生成建议' WHERE setting_key='ai.decision.enabled';
UPDATE system_settings SET remark='解锁全自动条件：近4周采纳率≥minAcceptRate% 且近 minWeeks 周连续达标 且已决策样本≥minDecided 条' WHERE setting_key='ai.decision.maturity';
UPDATE system_settings SET remark='两域各自三档：手动确认 / 半自动(生成草稿待确认) / 全自动(成熟度解锁后直接执行+留痕+可回滚)' WHERE setting_key='ai.decision.modes';
UPDATE system_settings SET remark='决策中心学习闭环执行标记' WHERE setting_key='ai.last_refresh';
UPDATE system_settings SET remark='每次生成沉默唤醒名单的最多人数(按余额排序取前 N)' WHERE setting_key='ai.touch.limit';
UPDATE system_settings SET remark='超过该天数无有效消费且有余额/未用券 → 进入「沉默唤醒」推送名单(原 30 天硬编码提升为可改)' WHERE setting_key='ai.touch.silent_days';
UPDATE system_settings SET remark='每日定时(HH:MM)' WHERE setting_key='ai.daily_report.time';
UPDATE system_settings SET remark='动销/周转打分 → 淘汰清仓清单 + 品类扩容建议进决策中心待处理建议流' WHERE setting_key='ai.assortment.enabled';
UPDATE system_settings SET remark='库存可售天数超过该值且动销低迷 → 进入淘汰清单' WHERE setting_key='ai.assortment.max_turnover_days';
UPDATE system_settings SET remark='动销统计窗口；窗口内动销天数 ≤阈值 且 库存偏高 → 建议淘汰' WHERE setting_key='ai.assortment.window_days';
UPDATE system_settings SET remark='开=临期调价档位(≤7天5折/≤15天7折/其余8.5折)不设成本底线，可直接建议低于进价的价格；关=维持进价×(1+成本底线毛利率)下限。滞销类建议不受此开关影响' WHERE setting_key='ai.pricing.expiry_below_cost';
UPDATE system_settings SET remark='在库批次剩余保质期 ≤ 该值进入调价建议' WHERE setting_key='ai.pricing.expiry_days';
UPDATE system_settings SET remark='智能调价的建议价至少保证该毛利率(0.05 = 至少加价 5%)' WHERE setting_key='ai.pricing.min_margin';
UPDATE system_settings SET remark='近 N 天无销售 且 库存 ≥ stale_qty 记滞销' WHERE setting_key='ai.pricing.stale_days';
UPDATE system_settings SET remark='滞销判定最低在库量' WHERE setting_key='ai.pricing.stale_qty';
UPDATE system_settings SET remark='开=补货建议一键转采购单时在单据「预算金额」记录预计采购成本快照，供货审批参考' WHERE setting_key='po.suggest_budget';
UPDATE system_settings SET remark='开=向供应商收取的费用自动计入分红池' WHERE setting_key='recon.fee_to_dividend';
UPDATE system_settings SET remark='开=结算单审核通过后，还需再点「确认已付款」才算完结；关=审核通过即完结' WHERE setting_key='recon.settle_pay_flow';
UPDATE system_settings SET remark='库存不足时仍允许退货出库(按负库存入账)' WHERE setting_key='stock.negative_return';
UPDATE system_settings SET remark='开=库存不足也允许卖出(系统记为负库存，进货后自动冲抵)；关=库存不足时拦截销售' WHERE setting_key='stock.negative_sales';
UPDATE system_settings SET remark='开启后：零/负库存商品可登记报损(无在库批次可归属时按无批次记账，成本取商品进货价)，审核跳过批次剩余校验' WHERE setting_key='stock.loss_allow_zero';
UPDATE system_settings SET remark='入库价低于历史最低进价时拦截(可强推)。属进销存业务规则，与 OCR 无关，放在「商品管理」' WHERE setting_key='ai.ocr.low_price';
UPDATE system_settings SET remark='入库价低于历史最低进价时的处理方式' WHERE setting_key='ai.ocr.low_price_mode';
UPDATE system_settings SET remark='建档/改档未填保质期的商品，禁止上架销售' WHERE setting_key='product.keep_days_required';
UPDATE system_settings SET remark='临期预警产生后，店长/店员须在该时限内处置到位(退换货流程完成)；超时未处置记处罚' WHERE setting_key='stock.expiry_disposal_hours';
UPDATE system_settings SET remark='商品临近保质期提前提醒：先黄色提示、后橙色加急；两个档位可改' WHERE setting_key='stock.expiry_warn_days';
UPDATE system_settings SET remark='每日爬虫补库次数上限，防触发反爬与流量滥用；0=禁用爬虫' WHERE setting_key='barcode.crawler.daily_limit';
UPDATE system_settings SET remark='全部数据源未命中时低频抓取必应中国结果标题补库(限速：码间≥3秒、每日≤上限)；结果标注"参考数据请核对"' WHERE setting_key='barcode.crawler.enable';
UPDATE system_settings SET remark='输码/扫码后自动查询本店库与在线条码库，预填商品名称/规格/单位/预估售价(只填空位不覆盖，均可修改)' WHERE setting_key='barcode.lookup.enable';
UPDATE system_settings SET remark='在 mxnzp.com 免费申请；填写后建档扫码可自动带出商品资料；留空=不使用该数据源' WHERE setting_key='barcode.lookup.mxnzp.app_id';
UPDATE system_settings SET remark='与上面 AppID 配套的密钥；加密保存，界面只显示尾号' WHERE setting_key='barcode.lookup.mxnzp.app_secret';
UPDATE system_settings SET remark='多券使用规则：manual=收银员手动多选(受每券「可叠加使用」开关约束)；single=一单仅用一张、系统自动取最优惠；auto=系统自动挑选可叠加组合求总抵扣最大' WHERE setting_key='coupon.mode';
UPDATE system_settings SET remark='开启=优惠券可与促销活动同单叠加；关闭=同单已有促销时用券会被拒绝' WHERE setting_key='coupon.stack_with_promo';
UPDATE system_settings SET remark='临期N天自动按档位折价：[{"days":剩余天数上限,"pct":售价百分数}](pct 80=8折)。按剩余保质期落入的区间匹配档位(天数从小到大，命中第一个 剩余天数≤days 的档)，越临期折越深；超出全部档位不折扣。收银自动折扣(promo.expiry_auto.enabled 开启时)与 AI 临期调价建议共用此档位' WHERE setting_key='promo.expiry_auto_discount';
UPDATE system_settings SET remark='开=收银结算时，购物车中有在库临期批次的商品自动按「临期自动折扣档位」折价(剩余天数≤days 取最深档)；与门店促销互斥(促销优先、临期兜底，防双重折扣)；低于进价由「临期商品豁免成交价下限闸」协同放行。默认关——开启前请先确认档位配置符合预期' WHERE setting_key='promo.expiry_auto.enabled';
UPDATE system_settings SET remark='商品行级优惠(特价/第二件半价)与整单级优惠(满减/满折)能否同时享受' WHERE setting_key='promo.stack_layers';
UPDATE system_settings SET remark='同一单同时命中多个促销时，自动按对顾客最优惠的一个执行' WHERE setting_key='promo.take_best';
UPDATE system_settings SET remark='开=会员可在 H5 手机号自助注册建档(含密保设置)；关=仅员工/后台建档。现由注册接口服务端消费' WHERE setting_key='member.h5.allow_register';
UPDATE system_settings SET remark='会员掌上门户(/member/ 登录·注册·找回)总开关：关=会员端登录注册接口全部返回维护中，仅员工代客操作' WHERE setting_key='member.h5.enabled';
UPDATE system_settings SET remark='会员手机访问的完整地址(如 https://192.168.1.10:3443/member/)；留空=后台自动按当前服务器地址拼接。设置页「会员 H5 入口」二维码与首页快捷入口使用此值' WHERE setting_key='member.h5.entry_url';
UPDATE system_settings SET remark='允许会员在 H5 用密码登录(关=暂停密码登录并提示门店协助；验证码登录依赖短信服务商接入后启用)' WHERE setting_key='member.login.password_h5';
UPDATE system_settings SET remark='会员建档勾选「隐私协议」处点击可查看全文；有系统设置权限者可在此更新(更新后新建档按新文本)' WHERE setting_key='member.privacy_text';
UPDATE system_settings SET remark='到时自动扫描生日/临期/分红到期并生成触达' WHERE setting_key='marketing.run_time';
UPDATE system_settings SET remark='未达免邮门槛时收取' WHERE setting_key='delivery.fee';
UPDATE system_settings SET remark='订单应付 ≥ 该值免配送费' WHERE setting_key='delivery.free_above';
UPDATE system_settings SET remark='0=不限；>0 时超出配送围栏拒绝配送(需门店坐标)' WHERE setting_key='delivery.radius_km';
UPDATE system_settings SET remark='开通后 H5 支持配送/外卖下单；关闭则仅支持到店自提' WHERE setting_key='delivery.serving';
UPDATE system_settings SET remark='配送围栏圆心纬度(delivery.radius_km>0 时生效)' WHERE setting_key='store.lat';
UPDATE system_settings SET remark='配送围栏圆心经度(delivery.radius_km>0 时生效)' WHERE setting_key='store.lng';
UPDATE system_settings SET remark='扫码购允许选微信/支付宝付款；当前为模拟通道记账(pay.gateway mode=mock)，真通道需已备案域名+商户号(外部资质)' WHERE setting_key='h5.direct_pay';
UPDATE system_settings SET remark='线上商城/扫码购总开关：关=会员端下单入口全面关闭(现由 member-app createOrder 服务端消费)。店内查询不受影响' WHERE setting_key='h5.enabled';
UPDATE system_settings SET remark='扫码购单笔应付上限(元，0=不设限)。现由下单服务端消费：超限拒单并提示转收银台' WHERE setting_key='h5.scan_go_limit';
UPDATE system_settings SET remark='关闭后成长值不再累计(已产生的成长值与等级仍保留)' WHERE setting_key='member.growth.enabled';
UPDATE system_settings SET remark='分类ID数组 JSON。整类消费不计成长值' WHERE setting_key='member.growth.exclude_categories';
UPDATE system_settings SET remark='商品ID数组 JSON。例 [12,35]；这些商品消费不计成长值(如香烟)' WHERE setting_key='member.growth.exclude_products';
UPDATE system_settings SET remark='命中特价/折扣活动的商品消费不计成长值' WHERE setting_key='member.growth.exclude_promo';
UPDATE system_settings SET remark='每充值 1 元本金计多少成长值。默认 1 元=1 分；赠送金额不计' WHERE setting_key='member.growth.recharge_rate';
UPDATE system_settings SET remark='每实付消费 1 元计多少成长值。默认 1 元=0.8 分；余额/券抵扣/赠送不计' WHERE setting_key='member.growth.consume_rate';
UPDATE system_settings SET remark='滚动考核窗口月数。默认近 6 个月成长值决定保级' WHERE setting_key='member.growth.period_months';
UPDATE system_settings SET remark='近考核周期成长值不达保级线后进入缓冲期，期间保留全部会员权益；期内补足成长即退出，到期仍不达标才正式下调。默认 30 天' WHERE setting_key='member.level_grace_days';
UPDATE system_settings SET remark='开启后每日 02:35 自动按昨日净利 × dividend.ratio 计提分红(幂等，与手动计提互斥)；关闭则仅手动计提' WHERE setting_key='dividend.auto.enabled';
UPDATE system_settings SET remark='每日自动分红计提与到期失效回冲的触发时刻(HH:MM，服务器本地时间)。到点后服务在线即补跑(幂等)，晚开机不会漏计提；建议设在日结(00:05)之后、备份时间之前' WHERE setting_key='dividend.auto.time';
UPDATE system_settings SET remark='每位会员累计领的分红 ≤ 其累计充值 × 该比例；达到封顶后新分红只发积分，不再发现金' WHERE setting_key='dividend.cap_rate';
UPDATE system_settings SET remark='过期未用的分红自动作废' WHERE setting_key='dividend.expire_days';
UPDATE system_settings SET remark='单笔消费满该金额才计入分红资格，防微额刷单' WHERE setting_key='dividend.min_single';
UPDATE system_settings SET remark='统计窗口内累计消费满该金额才具备分红资格' WHERE setting_key='dividend.min_window';
UPDATE system_settings SET remark='分红年化达到该比例时橙色预警，提醒关注分红支出' WHERE setting_key='dividend.orange_alert';
UPDATE system_settings SET remark='每日分红池 = 昨日净利润 × 该比例' WHERE setting_key='dividend.ratio';
UPDATE system_settings SET remark='分红年化达到该比例时红色预警，须立即干预(低于橙色档)' WHERE setting_key='dividend.red_alert';
UPDATE system_settings SET remark='「窗口内累计消费」的统计天数范围' WHERE setting_key='dividend.window_days';
UPDATE system_settings SET remark='开启后按会员等级打折计价' WHERE setting_key='member.level_discount';
UPDATE system_settings SET remark='连锁门店断网时允许会员余额先记账后清算(P2)。关闭(默认)= 断网时余额不可用，收银员改用其他支付方式' WHERE setting_key='member.offline.enabled';
UPDATE system_settings SET remark='断网挂账当日累计上限(含待清算与当日已清算)；超过则当日余额支付全部拒绝' WHERE setting_key='member.offline.max_daily';
UPDATE system_settings SET remark='断网挂账单笔上限；超过则拒绝余额支付(防大额资金风险)' WHERE setting_key='member.offline.max_single';
UPDATE system_settings SET remark='会员 H5 发起充值的单笔上限(元)，超出拒绝' WHERE setting_key='member.recharge.max_single';
UPDATE system_settings SET remark='充值单超过该时长未支付即失效，会员可取消后重新发起' WHERE setting_key='member.recharge.orders_expire_hours';
UPDATE system_settings SET remark='每月房租总额；日摊 = 月值 ÷ 当月天数，计入每日净利(分红基数)扣减' WHERE setting_key='store.cost.rent';
UPDATE system_settings SET remark='每月水电燃气等总额；按月估值日摊计入净利' WHERE setting_key='store.cost.utility';
UPDATE system_settings SET remark='设备装修等按月折旧摊销额；日摊计入净利' WHERE setting_key='store.cost.depreciation';
UPDATE system_settings SET remark='物业/网费/固定人工外包等其他月度固定支出；日摊计入净利' WHERE setting_key='store.cost.other';
UPDATE system_settings SET remark='收银台结算页可直接套用的命名折扣规则(rate=折数，如 95=95折)；自定义折扣率需 pos.discount.custom 权限' WHERE setting_key='pos.discount.presets';
UPDATE system_settings SET remark='取单列表默认范围：mine=只看本人挂的单；all=全店所有挂单(店长/主管查全店时用)。可临时切换，本开关为默认态' WHERE setting_key='pos.held.default_scope';
UPDATE system_settings SET remark='收银员改价/打折的授权频次：batch=一次授权后本单连续操作免再输码(票据120秒、结算作废)；once=每次改价都弹窗要求店长输授权码' WHERE setting_key='pos.price.auth_reuse';
UPDATE system_settings SET remark='on=持「改价/折扣授权」权限的员工本人在收银台操作价格时自动授权免输码(仍留痕，授权人=操作人)；off=本人操作同样需要输授权码(责任最严)' WHERE setting_key='pos.price.auth_self';
UPDATE system_settings SET remark='开班录入钱箱备用金的默认值' WHERE setting_key='pos.cashbox.float_default';
UPDATE system_settings SET remark='挂账单默认到期天数(超期进店长提醒列表)' WHERE setting_key='pos.credit.due_days';
UPDATE system_settings SET remark='实点与应答差异超过该值强制填写原因；0=不容差' WHERE setting_key='pos.shift.diff_tolerance';
UPDATE system_settings SET remark='单笔订单积分抵现金额不超过应收的该百分比(%)；0 或留空 = 不启用上限(可全额抵扣)' WHERE setting_key='pos.points.max_pct';
UPDATE system_settings SET remark='多少积分抵 1 元现金(如 100 = 100 积分抵 1 元)；0 = 关闭积分抵现。前台与后端均按此口径换算。' WHERE setting_key='pos.points.rate';
UPDATE system_settings SET remark='商品未设「最低卖价」时的价格红线 = 售价 × 本比率。0.8=最多打 8 折。超市毛利通常 ≤20%，不建议低于 0.8；设 1 表示不允许低于售价' WHERE setting_key='sales.floor_guard_rate';
UPDATE system_settings SET remark='开=同码 2 秒内连扫不重复加件(弹条可撤销，默认 2 秒)；关=关闭防抖' WHERE setting_key='pos.cashier.debounce';
UPDATE system_settings SET remark='本机设置：在收银台「设置」面板调整，仅本机生效；此处值仅作新收银台初始默认' WHERE setting_key='pos.cashier.grid_cols';
UPDATE system_settings SET remark='收银台键位映射 JSON：pay/hold/take/repeat/print/lock/stock 七槽；stock=库存查询(默认 F10)' WHERE setting_key='pos.cashier.hotkey_map';
UPDATE system_settings SET remark='键盘快捷键的新收银机初始默认值；F3 总开关在收银台本机生效(仅本机)' WHERE setting_key='pos.cashier.hotkeys';
UPDATE system_settings SET remark='收银台无操作自动锁屏时间(1~30 分钟，0=不自动锁)；默认 15 分钟' WHERE setting_key='pos.cashier.lock_timeout';
UPDATE system_settings SET remark='开=登录直落新收银台；关=回退旧版「作业-收银」视图(严重问题一键回退预案)' WHERE setting_key='pos.cashier.new_ui';
UPDATE system_settings SET remark='收银台快捷商品区默认展示格数(8~12)与编辑上限；本机自定义仍可覆盖' WHERE setting_key='pos.cashier.quick_count';
UPDATE system_settings SET remark='是=账实不符时超库存一律拒绝(谨慎型门店)；否=确认后按负库存售卖(留痕进负库存清单)' WHERE setting_key='pos.cashier.stock_hard';
UPDATE system_settings SET remark='收款成功后语音播报金额(收银台语音)' WHERE setting_key='pos.cashier.tts';
UPDATE system_settings SET remark='收银台专用；留空 = 跟随老板端「播报语速」' WHERE setting_key='pos.cashier.tts.rate';
UPDATE system_settings SET remark='收银台专用；留空 = 跟随老板端「播报音色」' WHERE setting_key='pos.cashier.tts.voice';
UPDATE system_settings SET remark='新会员注册/建档归属门店(决策②)；消费记账按实际交易门店(动态)，会员主档统一归总部' WHERE setting_key='member.hq_store_id';
UPDATE system_settings SET remark='小票抬头/收银台门头显示名(后台可改)；留空回退连锁门店档案的门店名。注意：address/contact/phone 三个同名前缀键已废弃删除，门店地址电话以「连锁管理-门店管理」档案为准' WHERE setting_key='store.info.name';
UPDATE system_settings SET remark='开=浮层与支付弹层用半透明磨砂玻璃质感(更精致)；关=改用普通实底色(低配收银机 / Win7 推荐关)' WHERE setting_key='ui.glass.enabled';
UPDATE system_settings SET remark='审计日志保留天数(0=关闭清理)：每日 00:10 超期行迁移 audit_logs_archive 后从主表删除' WHERE setting_key='auth.audit_retention';
UPDATE system_settings SET remark='员工/会员密码的强度要求：新建账号、修改密码、重置密码都按此校验' WHERE setting_key='auth.password_policy';
UPDATE system_settings SET remark='单据金额超过「大额签字阈值」时的确认方式' WHERE setting_key='auth.sign_large_mode';
UPDATE system_settings SET remark='勾选后对应单据必须签字才能过审' WHERE setting_key='auth.sign_required_scenes';
UPDATE system_settings SET remark='单据金额超过该值需短信确认或现场补签' WHERE setting_key='auth.sign_threshold';
UPDATE system_settings SET remark='现金收款结账成功后向钱箱发弹开指令(WebSerial 连接钱箱/RJ11 接小票机时生效)' WHERE setting_key='pos.drawer.enabled';
UPDATE system_settings SET remark='收银端连续无法访问服务器超过该秒数(WiFi 已连但局域网断/服务挂)→ 弹离线收银引导。与 navigator.onLine 双保险' WHERE setting_key='pos.heartbeat_timeout';
UPDATE system_settings SET remark='价目表超过该时长未更新则禁止进入应急收银；未命中商品仅限店长授权手输' WHERE setting_key='pos.pricebook_fresh_hours';
UPDATE system_settings SET remark='收银合计金额的抹零方式(只抹零、不多收)' WHERE setting_key='pos.round_rule';
UPDATE system_settings SET remark='退款金额 ≤ 限额直接执行；超过则创建为「待审核」，需 sales.refund.audit 权限审核' WHERE setting_key='sales.refund.limit';
UPDATE system_settings SET remark='按商品分类设置退货天数(1=仅限当天)。生鲜类建议 1 天，百货日化可放宽至 7 天；未在此列出的分类回退到 sales.refund.window_days' WHERE setting_key='sales.refund.window_by_category';
UPDATE system_settings SET remark='下单超过 N 天的订单不能在收银台退货；0 = 不限时间' WHERE setting_key='sales.refund.window_days';
UPDATE system_settings SET remark='在线支付(扫码付)下单后未收到支付结果的单，超过该分钟数自动关单并回冲库存(关单前先查支付通道确认未支付)；填 0 关闭自动关单' WHERE setting_key='sales.close_order_minutes';
UPDATE system_settings SET remark='开=在库临期批次(≤ai.pricing.expiry_days 天到期)的商品不计入成交价下限校验，临期折扣可低于进价销售(去化优先)；关=临期商品同样受下限闸约束' WHERE setting_key='sales.floor_guard_expiry_exempt';
UPDATE system_settings SET remark='开=整单优惠(促销/券/会员价/整单折扣/抹零)叠加后低于商品最低售价合计时，需店长现场授权(工号+授权码)才能收款，全额审计留痕；关=不拦截(不建议，正式开业请保持开启)' WHERE setting_key='sales.price_floor_guard';
UPDATE system_settings SET remark='开启后会员端可自助扫码购并生成核销码；核销抽检在收银台前台「扫码购核销」进行，后台仅展示流水' WHERE setting_key='sales.scanpay_enabled';
UPDATE system_settings SET remark='移动收银与作业模块的左右手镜像(已生效：扫码区/工具按钮/数量步进器按习惯反向排布)，端上读取后缓存到本地' WHERE setting_key='mobile.hand';
UPDATE system_settings SET remark='超过该月数的库存流水(stock_flows)每日 03:40 批量迁移 stock_flows_archive 后从主表删除；0=不归档。主表瘦身可显著加快库存查询与盘点' WHERE setting_key='ops.archive.flow_months';
UPDATE system_settings SET remark='超过该月数的 AI 识别日志(ai_recognition_logs)每日 03:40 批量迁移 ai_recognition_logs_archive 后从主表删除；0=不归档。难例挖掘等查询只查热表，归档表用于追溯' WHERE setting_key='ops.archive.recog_months';
UPDATE system_settings SET remark='全量+双硬盘轮换' WHERE setting_key='ops.backup_hour';
UPDATE system_settings SET remark='应急收银单笔金额上限(元)；日累计上限另行管控' WHERE setting_key='ops.emergency_amount_cap';
UPDATE system_settings SET remark='断网等应急场景下允许执行应急收银的角色' WHERE setting_key='ops.emergency_pay';
UPDATE system_settings SET remark='>0 时日报显示达成率；0=不设目标' WHERE setting_key='report.daily_target';
UPDATE system_settings SET remark='空=不解析秤码。模板字符：F前缀 W重量(克) E金额(分→元) N商品码 P单价(分→元) C校验 D忽略位 . 小数点，如 FWWWWWWEEEEEC' WHERE setting_key='ai.scale.barcode_format';
UPDATE system_settings SET remark='on=按 EAN mod10 验算秤码校验位(结构正确的假码拒收)；off=兼容非标算法的旧秤(跳过后置「未配置」提示重打)。改后需真机验证本店秤签算法' WHERE setting_key='ai.scale.check_verify';
UPDATE system_settings SET remark='条码秤格式选「自定义」时生效，字符集同上' WHERE setting_key='ai.scale.custom_format';
UPDATE system_settings SET remark='模板含 T 段(6位 YYMMDD 或 8位 YYYYMMDD 打印日期)时校验：超出 N 天或未来日期拒收；无 T 段的模板不受影响' WHERE setting_key='ai.scale.label_valid_days';
UPDATE system_settings SET remark='PWA 作业页未读经营告警的语音播报开关(收款播报另由 pos.voice_broadcast 控制)' WHERE setting_key='ai.voice.alerts';
UPDATE system_settings SET remark='审核通过后自动弹出 A5 单据打印(已接入：采购入库/采购退货/采购订单/盘点/报损/调拨/对账确认)，需 docs.print.a5 权限；是前端弹打印预览，非服务端静默打印' WHERE setting_key='doc.print.auto_a5';
UPDATE system_settings SET remark='打印机 USB 刷新后静默自动重连总闸：关=需到设备面板手动重连' WHERE setting_key='ops.printer_reconnect';
UPDATE system_settings SET remark='电子秤串口波特率(与秤说明书一致，常见 9600 / 4800)' WHERE setting_key='scale.baud';
UPDATE system_settings SET remark='电子秤自动读重总开关：关=收银时手动输重量(串口参数 scale.tx.* 见下)' WHERE setting_key='scale.enabled';
UPDATE system_settings SET remark='条码秤打印条码的前两位识别码(FFWWWWW 中的 FF)' WHERE setting_key='scale.tx.barcode_prefix';
UPDATE system_settings SET remark='常见 9600' WHERE setting_key='scale.tx.baud';
UPDATE system_settings SET remark='秤端编码(下拉选择，中文标签秤通用 GBK)' WHERE setting_key='scale.tx.charset';
UPDATE system_settings SET remark='2位部门号' WHERE setting_key='scale.tx.department';
UPDATE system_settings SET remark='如 COM3 / COM4' WHERE setting_key='scale.tx.port';
UPDATE system_settings SET remark='默认连接方式(下拉选择)' WHERE setting_key='scale.tx.port_type';
UPDATE system_settings SET remark='默认协议品牌(下拉选择)' WHERE setting_key='scale.tx.protocol';
UPDATE system_settings SET remark='网口秤 IP' WHERE setting_key='scale.tx.tcp_host';
UPDATE system_settings SET remark='常见 9100' WHERE setting_key='scale.tx.tcp_port';
UPDATE system_settings SET remark='是否同时下发会员价(依赖秤型号支持)' WHERE setting_key='scale.tx.use_member_price';
UPDATE system_settings SET remark='老板端「经营问答」答案自动朗读的开关(已生效，boss 端实时读取)；音色/语速在「语音播报」小节统一配置' WHERE setting_key='voice.assistant.enabled';
UPDATE system_settings SET remark='语音提问查价的回答播报；音色/语速在「语音播报」小节统一配置' WHERE setting_key='voice.price.enabled';
UPDATE system_settings SET remark='收银加购时播报商品名+价格(在 pos.cashier.tts 总开关之下的子开关)' WHERE setting_key='voice.product.enabled';
UPDATE system_settings SET remark='0.5~2 倍，1 为正常语速；收款播报建议 1~1.2' WHERE setting_key='voice.tts.rate';
UPDATE system_settings SET remark='空=自动选最佳中文声(女声优先)；设置页可下拉试听本机全部音色，带 ⭐ 为拟真人声' WHERE setting_key='voice.tts.voice';
UPDATE system_settings SET remark='开=员工登录必须使用「已授权设备」，新设备自动登记为待授权并上报管理后台；关=任何人知道账密即可在任意设备登录(不建议)' WHERE setting_key='pos.device.auth';
UPDATE system_settings SET remark='从服务器本机(127.0.0.1 / ::1)发起的登录跳过设备授权校验，用于避免「授权需要登录、登录需要授权」的引导死锁。手机与局域网其它电脑不受影响，仍须授权。不接受可关闭，但关闭后管理员换设备须靠恢复码或 npm run device:grant 解封' WHERE setting_key='pos.device.auth.loopback.bypass';
UPDATE system_settings SET remark='默认关。收银台为共用设备，一台设备需服务多个员工；开启后会变成「一台设备固定一个员工」，导致其他员工登不进。设备准入请用「配对码」' WHERE setting_key='pos.device.bind.employee';
UPDATE system_settings SET remark='收银员、库管 默认只允许 1 台设备(一台设备固定一个员工)；共享收银台请调高或关闭「设备绑定员工」' WHERE setting_key='pos.device.limit.cashier';
UPDATE system_settings SET remark='店长、财务、超级管理员 默认允许 2 台(手机 + 电脑/_PAD 各一)；超管另有应急恢复码兜底' WHERE setting_key='pos.device.limit.manager';
UPDATE system_settings SET remark='1 = 只能用一次(最安全)。共用收银台要一次放行多台时生成「不限次」码，或给每台设备分别生成一个码' WHERE setting_key='pos.device.pair.max.uses';
UPDATE system_settings SET remark='管理员生成的配对码在多少小时后失效。当天配对建议 24；跨天审批可设 72。过期后员工需重新找管理员要码' WHERE setting_key='pos.device.pair.ttl.hours';
UPDATE system_settings SET remark='超管被挡在门外时的兜底：登录时填写此码可强制通过并自动授权本设备。留空表示未启用(改用环境变量 DEVICE_RECOVERY_CODE)。生成后请妥善保管' WHERE setting_key='pos.device.recovery.hint';
UPDATE system_settings SET remark='开=设备必须用硬件私钥对登录挑战签名(设备码被抄到别的电脑/手机也登不进去)。需前端与 APK 均升级后再开启，否则旧设备全部无法登录' WHERE setting_key='pos.device.require.signature';
UPDATE system_settings SET remark='开=新设备登录后，旧设备的会话在 60 秒内失效(防同账号多地同时收银/改价)；关=允许多设备同时在线' WHERE setting_key='pos.device.single.session';
UPDATE system_settings SET remark='单个门店最多可登记的授权设备数(含待授权)。按「收银台数 + 老板/店长手机 + 备用机」的 1.5 倍设定，随时可调。超出后新设备无法登记' WHERE setting_key='pos.device.store.cap';
UPDATE system_settings SET remark='顾客副屏空闲轮播(JSON 数组：[{title,sub,emoji,image?}]，后台设置页可编辑)' WHERE setting_key='display.ads';
UPDATE system_settings SET remark='顾客副屏顶栏常驻欢迎语(店招取「商店信息 store.info.name」)' WHERE setting_key='display.welcome';
UPDATE system_settings SET remark='开=收银台全屏并强制置顶(盖住任务栏、Alt+Tab 也切不走，适合顾客可触碰的收银机)；关=全屏但可切换其他程序(默认)' WHERE setting_key='pos.desktop.kiosk_topmost';
UPDATE system_settings SET remark='关闭后主屏不再向顾客副屏推送购物明细/支付引导(副屏显示等待连接)' WHERE setting_key='pos.display.push';
UPDATE system_settings SET remark='小票机自动出票总开关(已配默认小票机时生效)；没配小票机走浏览器兜底，由「浏览器兜底打印」控制' WHERE setting_key='pos.print.auto';
UPDATE system_settings SET remark='未配置小票机时：开=自动弹浏览器打印预览兜底出票；关=绝不弹预览(明示未出票，可补打)。与小票机路径的「结账自动打印小票」互补' WHERE setting_key='pos.print.browser_fallback';
UPDATE system_settings SET remark='每单打印联数(默认 1；双联存根请设 2)' WHERE setting_key='pos.print.copies';
UPDATE system_settings SET remark='浏览器打印路径的自动出票开关(receipt 模块)；是否走浏览器兜底路径由「浏览器兜底打印」决定，本键只管该路径内是否自动打' WHERE setting_key='pos.receipt.auto_print';
UPDATE system_settings SET remark='小票纸宽度(毫米，常见 80 / 58，与打印机实际纸宽一致)' WHERE setting_key='pos.receipt.width';
UPDATE system_settings SET remark='收银完成后的收款金额语音提示(「收款 X 元，谢谢惠顾」)；音色在「语音播报」小节选择' WHERE setting_key='pos.voice_broadcast';
UPDATE system_settings SET remark='门店开业日期(YYYY-MM-DD)，作为经营报表起算日与会员分红资格窗口的基准' WHERE setting_key='init.opening_date';
UPDATE system_settings SET remark='开业日(init.opening_date)当天 00:06 起向全员广播本说明一次(员工端铃铛+老板端消息中心)；留空=不广播' WHERE setting_key='init.opening_note';
UPDATE system_settings SET remark='最多保留最近 N 份备份，超出循环删除最旧的一份(0=不限，仅按天数过期)；与「每日备份时间」「保留天数」共同生效' WHERE setting_key='ops.backup.keep_count';
UPDATE system_settings SET remark='备份目录总占用超过该值时，从最旧的备份开始删除直到达标(0=不按大小限制，仅按份数/天数清理)' WHERE setting_key='ops.backup.max_total_gb';
UPDATE system_settings SET remark='进价差异单超时未裁决 → 自动结案(认可)并升级告警' WHERE setting_key='chain.cost.adjust_window_h';
UPDATE system_settings SET remark='总部还没维护过某商品进价时，第一笔入库的实际进价自动作为标准进价，新品立即受进价保护' WHERE setting_key='chain.cost.auto_adopt_new';
UPDATE system_settings SET remark='同店同商品同向差异在该窗口内合并为一条，防刷屏' WHERE setting_key='chain.cost.merge_days';
UPDATE system_settings SET remark='关=门店申请新商品上架需要总部批准；开=申请后直接生效' WHERE setting_key='chain.product.self_apply';
UPDATE system_settings SET remark='true=允许受理店以现金直接退付他店订单(资金走店间往来台账)；false=强制走跨店冲减流程。默认关' WHERE setting_key='chain.return.cross_cash';
UPDATE system_settings SET remark='true=盘点盈余按棘轮规则允许抬高 L1 进价基准；false=盘盈只调数量不调价' WHERE setting_key='chain.variance.pickup_raise_l1';
UPDATE system_settings SET remark='单节点单日「退款/回补」入向总额上限，防会员资产被凭空增发(审计 F-02)。0=不限制(不建议)' WHERE setting_key='hq.member.cross_daily_limit';
